name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }] # every hour
  push: { branches: ["master", "main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Youssef-joe
          base: activity, community, repositories, metadata
          config_timezone: Africa/Cairo
          plugin_traffic: yes
          plugin_followup: yes
          plugin_lines: yes
          plugin_isocalendar: yes
